# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Apache.Thrift
PackageVersion: 0.25.0
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{064E0C5D-29EE-47DD-BB5E-172FE25FE936}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/apache/thrift/releases/download/v0.25.0/thrift-0.25.0-setup.exe
  InstallerSha256: C94286CB0422F02CBF0032931C85CFBA5940E13EFCCF10C1F5CF21B1398FD666
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-30
